SELECT 
    ID_PROCEDIMENTO, 
    NUM_BO, 
    CO_REGISTRO_NACIONAL, 
    NO_NATUREZA_OCORRENCIA, 
    DT_HORA_REGISTRO, 
    DT_OCORRENCIA, 
    HO_OCORRENCIA, 
    ID_UF, 
    NO_MUNICIPIO, 
    ED_BAIRRO, 
    'ENDERECO_SUPRIMIDO' AS ED_LOGRADOURO, 
    'NUM_SUPRIMIDO' AS ED_NUMERO, 
    'ENDERECO_SUPRIMIDO' AS ED_COMPLEMENTO, 
    'CEP_SUPRIMIDO' AS ED_CEP, 
    DS_LOCAL_OCORRENCIA, 
    'ENDERECO_SUPRIMIDO' AS DS_PTO_REF_OCORRENCIA, 
    ED_LATITUDE_LONGITUDE, 
    'TEXTO_SUPRIMIDO' AS RELATO_HISTORICO, 
    IN_SITUACAO_ATUAL, 
    IN_TIPO_PROCEDIMENTO, 
    TP_INSTAURACAO, 
    SN_TENTATIVA, 
    SN_MARIA_DA_PENHA, 
    SN_SIGILOSO, 
    DS_GRUPO_NATUREZA
FROM DAAS.VW_BOLETIM_OCORRENCIA
WHERE DT_OCORRENCIA >= TO_DATE('2025-01-01', 'YYYY-MM-DD')
  AND DT_OCORRENCIA <  TO_DATE('2026-01-01', 'YYYY-MM-DD');
