SELECT 
    STATUS, 
    ID_CMORTE, 
    NIC_IML, 
    'VITIMA_' || TO_CHAR(ID_CMORTE) AS NOME_VITIMA, 
    TRUNC(DATA_NASCIMENTO_VITIMA, 'YEAR') AS DATA_NASCIMENTO_VITIMA, 
    'MAE_' || TO_CHAR(ID_CMORTE) AS MAE_VITIMA, 
    BAIRRO_OCORRENCIA, 
    CIDADE_OCORRENCIA, 
    DATA_ENTRADA, 
    DATA_OBITO, 
    TIPO_MORTE
FROM VW_IML_STATUS
WHERE DATA_ENTRADA >= TO_DATE('2025-01-01', 'YYYY-MM-DD')
  AND DATA_ENTRADA <  TO_DATE('2026-01-01', 'YYYY-MM-DD');
