-- ====================================================================
-- SCRIPT DE EXTRAÇÃO DE AMOSTRA CEGA (MOCK DATA)
-- Limita a 100 linhas e aplica mascaramento SQL direto nas chaves PII
-- ====================================================================

-- 1. Mock de CONTROLE_MORTE
CREATE OR REPLACE VIEW MOCK_CONTROLE_MORTE AS
SELECT 
    ID_CONTROLE_MORTE,
    'VITIMA_' || ID_CONTROLE_MORTE AS NOME_VITIMA,
    'MAE_' || ID_CONTROLE_MORTE AS MAE_VITIMA,
    'ALCUNHA_' || ID_CONTROLE_MORTE AS ALCUNHA_VITIMA,
    TRUNC(NASC_VITIMA, 'YEAR') AS NASC_VITIMA_ANO,
    'ENDERECO SUPRIMIDO' AS ENDERECO_VITIMA,
    NULL AS LATITUDE_VITIMA,
    NULL AS LONGITUDE_VITIMA,
    'HISTORICO SUPRIMIDO' AS HISTORICO_PC,
    NIC,
    BO_PC,
    CAD,
    AISP,
    RISP,
    BAIRRO_FATO,
    LATITUDE,
    LONGITUDE,
    DATA_HORA_FATO,
    SUBJETIVIDADE,
    STATUS_NECROPSIA,
    ALTER_DATE
FROM NEAC.CONTROLE_MORTE
WHERE ROWNUM <= 100;

-- 2. Mock de DADOS_AUTOR
CREATE OR REPLACE VIEW MOCK_DADOS_AUTOR AS
SELECT 
    ID_DADOS_AUTOR,
    ID_CM_DA_FK,
    'AUTOR_' || ID_DADOS_AUTOR AS NOME_AUTOR,
    '***.***.***-**' AS CPF_AUTOR,
    'ALCUNHA_' || ID_DADOS_AUTOR AS ALCUNHA_AUTOR,
    'ENDERECO SUPRIMIDO' AS ENDERECO_AUTOR,
    IDADE_AUTOR,
    SEXO_AUTOR,
    ESCOLARIDADE_AUTOR,
    SITUACAO_AUTOR,
    ARMA_UTILIZADA,
    VEICULO_UTILIZADO_AUTOR,
    ALTER_DATE
FROM NEAC.DADOS_AUTOR
WHERE ROWNUM <= 100;

-- 3. Mock de VIEW_IML_NEAC_CADAVERICO
CREATE OR REPLACE VIEW MOCK_IML_CADAVERICO AS
SELECT 
    NIC,
    'VITIMA_IML_' || NIC AS NOM_VITIMA,
    'SUPRIMIDO' AS PAI,
    'SUPRIMIDO' AS MAE,
    '***.***.*' AS RG,
    'SUPRIMIDO' AS TELEFONE,
    'SUPRIMIDO' AS LOGRADOURO,
    DATA_ENTRADA,
    DAT_OBITO,
    TIPO_EXAME,
    DSC_UNIDADE_IML,
    SEXO,
    ETNIA
FROM SGOU.VIEW_IML_NEAC_CADAVERICO
WHERE ROWNUM <= 100;

-- 4. Mock de VW_BOLETIM_OCORRENCIA
CREATE OR REPLACE VIEW MOCK_BOLETIM_OCORRENCIA AS
SELECT 
    ID_PROCEDIMENTO,
    NUM_BO,
    CO_REGISTRO_NACIONAL,
    NO_NATUREZA_OCORRENCIA,
    DS_GRUPO_NATUREZA,
    DT_HORA_REGISTRO,
    DT_OCORRENCIA,
    'SUPRIMIDO' AS ED_LOGRADOURO,
    'SUPRIMIDO' AS ED_NUMERO,
    'SUPRIMIDO' AS ED_COMPLEMENTO,
    'RELATO HISTORICO SUPRIMIDO PARA FINS DE MOCK' AS RELATO_HISTORICO,
    IN_SITUACAO_ATUAL
FROM DAAS.VW_BOLETIM_OCORRENCIA
WHERE ROWNUM <= 100;
