-- ====================================================================
-- SCRIPT DE POPULAÇÃO DO CATÁLOGO DE MASCARAMENTO (AGENTE LGPD)
-- ====================================================================

-- Tabela: CONTROLE_MORTE (NEAC)
INSERT INTO SENTINELA_MASCARAMENTO (TABELA_NOME, COLUNA_NOME, TIPO_MASCARA, JUSTIFICATIVA) VALUES ('CONTROLE_MORTE', 'NOME_VITIMA', 'PSEUDONIM', 'Identificação direta da vítima');
INSERT INTO SENTINELA_MASCARAMENTO (TABELA_NOME, COLUNA_NOME, TIPO_MASCARA, JUSTIFICATIVA) VALUES ('CONTROLE_MORTE', 'MAE_VITIMA', 'PSEUDONIM', 'Identificação indireta familiar');
INSERT INTO SENTINELA_MASCARAMENTO (TABELA_NOME, COLUNA_NOME, TIPO_MASCARA, JUSTIFICATIVA) VALUES ('CONTROLE_MORTE', 'ALCUNHA_VITIMA', 'PSEUDONIM', 'Identificação indireta');
INSERT INTO SENTINELA_MASCARAMENTO (TABELA_NOME, COLUNA_NOME, TIPO_MASCARA, JUSTIFICATIVA) VALUES ('CONTROLE_MORTE', 'NASC_VITIMA', 'TRUNCAR', 'Data de nascimento exata é PII. Truncar para ano.');
INSERT INTO SENTINELA_MASCARAMENTO (TABELA_NOME, COLUNA_NOME, TIPO_MASCARA, JUSTIFICATIVA) VALUES ('CONTROLE_MORTE', 'ENDERECO_VITIMA', 'SUPRIMIR', 'Endereço residencial exato');
INSERT INTO SENTINELA_MASCARAMENTO (TABELA_NOME, COLUNA_NOME, TIPO_MASCARA, JUSTIFICATIVA) VALUES ('CONTROLE_MORTE', 'LATITUDE_VITIMA', 'SUPRIMIR', 'Coordenada exata da residência');
INSERT INTO SENTINELA_MASCARAMENTO (TABELA_NOME, COLUNA_NOME, TIPO_MASCARA, JUSTIFICATIVA) VALUES ('CONTROLE_MORTE', 'LONGITUDE_VITIMA', 'SUPRIMIR', 'Coordenada exata da residência');
INSERT INTO SENTINELA_MASCARAMENTO (TABELA_NOME, COLUNA_NOME, TIPO_MASCARA, JUSTIFICATIVA) VALUES ('CONTROLE_MORTE', 'HISTORICO_PC', 'SUPRIMIR', 'Texto livre com narrativas e possíveis nomes');
INSERT INTO SENTINELA_MASCARAMENTO (TABELA_NOME, COLUNA_NOME, TIPO_MASCARA, JUSTIFICATIVA) VALUES ('CONTROLE_MORTE', 'HISTORICO_PM', 'SUPRIMIR', 'Texto livre com narrativas e possíveis nomes');
INSERT INTO SENTINELA_MASCARAMENTO (TABELA_NOME, COLUNA_NOME, TIPO_MASCARA, JUSTIFICATIVA) VALUES ('CONTROLE_MORTE', 'HISTORICO_IC', 'SUPRIMIR', 'Texto livre com narrativas e possíveis nomes');

-- Tabela: DADOS_AUTOR (NEAC)
INSERT INTO SENTINELA_MASCARAMENTO (TABELA_NOME, COLUNA_NOME, TIPO_MASCARA, JUSTIFICATIVA) VALUES ('DADOS_AUTOR', 'NOME_AUTOR', 'PSEUDONIM', 'Identificação direta do suspeito/autor');
INSERT INTO SENTINELA_MASCARAMENTO (TABELA_NOME, COLUNA_NOME, TIPO_MASCARA, JUSTIFICATIVA) VALUES ('DADOS_AUTOR', 'CPF_AUTOR', 'HASH', 'Documento sensível');
INSERT INTO SENTINELA_MASCARAMENTO (TABELA_NOME, COLUNA_NOME, TIPO_MASCARA, JUSTIFICATIVA) VALUES ('DADOS_AUTOR', 'ALCUNHA_AUTOR', 'PSEUDONIM', 'Apelido do autor');
INSERT INTO SENTINELA_MASCARAMENTO (TABELA_NOME, COLUNA_NOME, TIPO_MASCARA, JUSTIFICATIVA) VALUES ('DADOS_AUTOR', 'ENDERECO_AUTOR', 'SUPRIMIR', 'Endereço residencial do autor');

-- Tabela: VIEW_IML_NEAC_CADAVERICO (SGOU)
INSERT INTO SENTINELA_MASCARAMENTO (TABELA_NOME, COLUNA_NOME, TIPO_MASCARA, JUSTIFICATIVA) VALUES ('VIEW_IML_NEAC_CADAVERICO', 'NOM_VITIMA', 'PSEUDONIM', 'Nome da vítima no IML');
INSERT INTO SENTINELA_MASCARAMENTO (TABELA_NOME, COLUNA_NOME, TIPO_MASCARA, JUSTIFICATIVA) VALUES ('VIEW_IML_NEAC_CADAVERICO', 'PAI', 'SUPRIMIR', 'Nome do pai');
INSERT INTO SENTINELA_MASCARAMENTO (TABELA_NOME, COLUNA_NOME, TIPO_MASCARA, JUSTIFICATIVA) VALUES ('VIEW_IML_NEAC_CADAVERICO', 'MAE', 'SUPRIMIR', 'Nome da mãe');
INSERT INTO SENTINELA_MASCARAMENTO (TABELA_NOME, COLUNA_NOME, TIPO_MASCARA, JUSTIFICATIVA) VALUES ('VIEW_IML_NEAC_CADAVERICO', 'RG', 'HASH', 'Documento RG do IML');
INSERT INTO SENTINELA_MASCARAMENTO (TABELA_NOME, COLUNA_NOME, TIPO_MASCARA, JUSTIFICATIVA) VALUES ('VIEW_IML_NEAC_CADAVERICO', 'TELEFONE', 'SUPRIMIR', 'Contato telefônico');
INSERT INTO SENTINELA_MASCARAMENTO (TABELA_NOME, COLUNA_NOME, TIPO_MASCARA, JUSTIFICATIVA) VALUES ('VIEW_IML_NEAC_CADAVERICO', 'LOGRADOURO', 'SUPRIMIR', 'Endereço (IML)');

-- Tabela: VW_BOLETIM_OCORRENCIA (DAAS)
INSERT INTO SENTINELA_MASCARAMENTO (TABELA_NOME, COLUNA_NOME, TIPO_MASCARA, JUSTIFICATIVA) VALUES ('VW_BOLETIM_OCORRENCIA', 'RELATO_HISTORICO', 'SUPRIMIR', 'Narrativa completa do BO (Polícia Civil)');
INSERT INTO SENTINELA_MASCARAMENTO (TABELA_NOME, COLUNA_NOME, TIPO_MASCARA, JUSTIFICATIVA) VALUES ('VW_BOLETIM_OCORRENCIA', 'ED_LOGRADOURO', 'SUPRIMIR', 'Endereço da ocorrência no BO');

COMMIT;
