-- DDL para a tabela de log de reconciliação/divergências do SENTINELA

CREATE TABLE SENTINELA_RECONCILIACAO_LOG (
    ID_RECONCILIACAO  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ID_CONTROLE_MORTE NUMBER NOT NULL,
    FONTE             VARCHAR2(20) NOT NULL,   -- 'IML', 'CAD', 'PPE'
    CAMPO_MESTRA      VARCHAR2(100) NOT NULL,  -- Nome do campo na Controle Morte (ex: 'NOME_VITIMA')
    VALOR_MESTRA      VARCHAR2(4000),          -- Valor contido na Controle Morte
    CAMPO_FONTE       VARCHAR2(100) NOT NULL,  -- Nome do campo na fonte original (ex: 'NOM_VITIMA')
    VALOR_FONTE       VARCHAR2(4000),          -- Valor contido na fonte original (ou score de correlação)
    TIPO_DIVERGENCIA  VARCHAR2(50) NOT NULL,   -- 'VALOR_DIFERENTE', 'CAMPO_VAZIO_MESTRA', 'CORRELACAO_PROBABILISTICA'
    SCORE_SIMILARIDADE NUMBER,                 -- Percentual calculado de similaridade (ex: 88 ou score de 0-100)
    DT_DETECCAO       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    STATUS            VARCHAR2(30) DEFAULT 'Pendente', -- 'Pendente', 'Confirmado', 'Ignorado'
    DT_RESOLUCAO      TIMESTAMP
);

-- Índices recomendados para otimização das buscas e paginação na API
CREATE INDEX IDX_RECON_MESTRA ON SENTINELA_RECONCILIACAO_LOG(ID_CONTROLE_MORTE);
CREATE INDEX IDX_RECON_FONTE ON SENTINELA_RECONCILIACAO_LOG(FONTE);
CREATE INDEX IDX_RECON_STATUS ON SENTINELA_RECONCILIACAO_LOG(STATUS);
