import logging
from .retry_handler import with_retry

logger = logging.getLogger(__name__)

class AlertDispatcher:
    """
    Handles the dispatching of alerts generated by the ChangeDetector.
    Routes alerts to the appropriate notification services or message queues.
    """
    def __init__(self, notification_client):
        self.notifier = notification_client

    def dispatch_alerts(self, detected_changes):
        """
        Parses the detected changes and dispatches alerts accordingly.
        """
        logger.info("Dispatching alerts for detected changes.")
        
        if not detected_changes:
            logger.info("No changes to dispatch.")
            return
            
        evolutions = detected_changes.get("evolucao_para_obito", [])
        for evolution in evolutions:
            self._send_evolution_alert(evolution)
            
        crossings = detected_changes.get("bo_pc_crossings", [])
        for crossing in crossings:
            self._send_crossing_alert(crossing)

    @with_retry(max_retries=3, delay=1)
    def _send_evolution_alert(self, evolution_data):
        """
        Formats and sends an alert for an 'Evolucao para Obito' event.
        These are usually high-priority alerts.
        """
        # message = f"CRITICAL: Evolucao para Obito detected! Tentativa ID: {evolution_data.get('tentativa_id')} -> IML ID: {evolution_data.get('iml_id')}"
        # logger.warning(message)
        # self.notifier.send_urgent(message, context=evolution_data)
        pass

    @with_retry(max_retries=3, delay=1)
    def _send_crossing_alert(self, crossing_data):
        """
        Formats and sends an alert for a BO_PC cross-reference event.
        """
        # message = f"INFO: BO_PC Cross-reference found across systems. BO_PC: {crossing_data.get('bo_pc')}"
        # logger.info(message)
        # self.notifier.send_info(message, context=crossing_data)
        pass
