-- Views Seguras e Não-Bloqueantes do Módulo SENTINELA

-- 1. View Central do Analista (Morte + Autoria + IML + PC)
CREATE OR REPLACE VIEW VW_SENTINELA_CASO_COMPLETO AS
SELECT
    -- Chaves Universais
    CM.ID_CONTROLE_MORTE, CM.NIC, CM.BO_PC, CM.CAD,
    -- Local e Tempo
    CM.AISP, CM.RISP, CM.BAIRRO_FATO, CM.LATITUDE, CM.LONGITUDE, CM.DATA_HORA_FATO,
    -- Dados da Ocorrência
    CM.SUBJETIVIDADE, CM.INSTRUMENTO_UTILIZADO,
    -- Nomes da Vítima (Divergências)
    CM.NOME_VITIMA,
    IML.NOM_VITIMA AS NOM_VITIMA_IML,
    -- Integração IML (SGOU)
    IML.DATA_ENTRADA AS IML_ENTRADA,
    IML.TIPO_EXAME AS IML_EXAME,
    -- Integração Polícia Civil (DAAS)
    PC.DT_HORA_REGISTRO AS PC_DATA_REGISTRO,
    PC.DS_GRUPO_NATUREZA AS PC_NATUREZA,
    -- Resumo Autoria (NEAC)
    DA.QTD_AUTORES,
    -- Máscaras (Agente LGPD)
    'VITIMA_' || CM.ID_CONTROLE_MORTE AS NOME_VITIMA_MASK
FROM NEAC.CONTROLE_MORTE CM
LEFT JOIN SGOU.VIEW_IML_NEAC_CADAVERICO IML ON CM.NIC = IML.NIC
LEFT JOIN DAAS.VW_BOLETIM_OCORRENCIA PC ON CM.BO_PC = PC.NUM_BO
LEFT JOIN (
    SELECT ID_CM_DA_FK, COUNT(*) AS QTD_AUTORES 
    FROM NEAC.DADOS_AUTOR GROUP BY ID_CM_DA_FK
) DA ON CM.ID_CONTROLE_MORTE = DA.ID_CM_DA_FK;

-- 2. View Segura do IML (Sem PII explícito)
CREATE OR REPLACE VIEW VW_SENTINELA_CVLI_IML_SEGURA AS
SELECT
    NIC,
    DATA_ENTRADA,
    TIPO_EXAME,
    'IML_VITIMA_' || NIC AS NOME_VITIMA_MASK
FROM SGOU.VIEW_IML_NEAC_CADAVERICO;

-- 3. View Segura de Autoria (Sem PII explícito)
CREATE OR REPLACE VIEW VW_SENTINELA_AUTORIA_SEGURA AS
SELECT
    ID_AUTOR,
    ID_CM_DA_FK,
    'AUTOR_' || ID_AUTOR AS NOME_AUTOR_MASK,
    '***.***.***-**' AS CPF_AUTOR_MASK,
    IDADE_APARENTE,
    STATUS_PRISAO
FROM NEAC.DADOS_AUTOR;

-- 4. View de Mapa de Violência (Apenas Localização e Tipificação)
CREATE OR REPLACE VIEW VW_SENTINELA_MAPA_VIOLENCIA AS
SELECT
    ID_CONTROLE_MORTE,
    AISP,
    RISP,
    BAIRRO_FATO,
    LATITUDE,
    LONGITUDE,
    DATA_HORA_FATO,
    SUBJETIVIDADE
FROM NEAC.CONTROLE_MORTE
WHERE LATITUDE IS NOT NULL AND LONGITUDE IS NOT NULL;

-- 5. View de Quality Score (Completude das Chaves Universais)
CREATE OR REPLACE VIEW VW_SENTINELA_QUALITY_SCORE AS
SELECT
    AISP,
    RISP,
    COUNT(ID_CONTROLE_MORTE) AS TOTAL_CASOS,
    SUM(CASE WHEN NIC IS NOT NULL THEN 1 ELSE 0 END) AS CASOS_COM_NIC,
    SUM(CASE WHEN BO_PC IS NOT NULL THEN 1 ELSE 0 END) AS CASOS_COM_BOPC,
    SUM(CASE WHEN CAD IS NOT NULL THEN 1 ELSE 0 END) AS CASOS_COM_CAD,
    ROUND((SUM(CASE WHEN NIC IS NOT NULL THEN 1 ELSE 0 END) + 
           SUM(CASE WHEN BO_PC IS NOT NULL THEN 1 ELSE 0 END) + 
           SUM(CASE WHEN CAD IS NOT NULL THEN 1 ELSE 0 END)) / 
           (COUNT(ID_CONTROLE_MORTE) * 3) * 100, 2) AS QUALITY_SCORE_PERCENTUAL
FROM NEAC.CONTROLE_MORTE
GROUP BY AISP, RISP;

-- 6. View de SLA do Analista
CREATE OR REPLACE VIEW VW_SENTINELA_SLA_ANALISTA AS
SELECT
    A.ID_ANALISTA,
    COUNT(F.ID_ALERTA) AS TOTAL_ALERTAS_ATRIBUIDOS,
    SUM(CASE WHEN F.STATUS = 'Resolvido' THEN 1 ELSE 0 END) AS ALERTAS_RESOLVIDOS,
    AVG(CASE WHEN F.STATUS = 'Resolvido' THEN EXTRACT(DAY FROM (F.DT_ATUALIZACAO - F.DT_CRIACAO)) ELSE NULL END) AS SLA_MEDIO_DIAS
FROM SENTINELA_ATRIBUICAO A
JOIN SENTINELA_FILA_ALERTAS F ON A.ID_ALERTA = F.ID_ALERTA
GROUP BY A.ID_ANALISTA;
