import sqlite3
import re

def update_database():
    db_path = "sentinela.db"
    ddl_path = "database/ddl/sentinela_evolucao.sql"
    
    print(f"Lendo DDL de {ddl_path}...")
    with open(ddl_path, "r", encoding="utf-8") as f:
        ddl_content = f.read()
    
    # Adaptando o DDL para o SQLite (removendo GENERATED BY DEFAULT AS IDENTITY e NUMBER)
    # SQLite usa AUTOINCREMENT e INTEGER
    ddl_content = ddl_content.replace("NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", "INTEGER PRIMARY KEY AUTOINCREMENT")
    ddl_content = ddl_content.replace("NUMBER(1)", "INTEGER")
    ddl_content = ddl_content.replace("NUMBER", "INTEGER")
    ddl_content = ddl_content.replace("VARCHAR2", "VARCHAR")
    ddl_content = ddl_content.replace("TIMESTAMP", "DATETIME")
    
    # Separando os comandos SQL por ponto e vírgula
    commands = re.split(r';', ddl_content)
    
    print(f"Conectando ao banco SQLite em {db_path}...")
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()
    
    for cmd in commands:
        cmd = cmd.strip()
        if not cmd:
            continue
        try:
            print(f"Executando: {cmd[:50]}...")
            cursor.execute(cmd)
        except sqlite3.OperationalError as e:
            # Se a tabela já existir, ignoramos o erro
            if "already exists" in str(e):
                print(f"  [Aviso] Objeto já existente: {e}")
            else:
                print(f"  [Erro] Falha ao executar comando: {e}")
                raise e
                
    conn.commit()
    conn.close()
    print("Atualização do banco de dados concluída com sucesso!")

if __name__ == "__main__":
    update_database()
